import requests
import json
import os

# Configuration
FASTAPI_URL = "http://127.0.0.1:8000/compress/chat"
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
# Make sure your GROQ_API_KEY environment variable is set in your terminal
GROQ_API_KEY = os.getenv("GROQ_API_KEY") 

# Define Ground-Truth Questions & Answers based on the original full context
EVALUATION_SUITE = [
    {
        "question": "What is the size of the legacy PostgreSQL database being migrated?",
        "ground_truth": "4.2 TB"
    },
    {
        "question": "Who is the network layer manager responsible for the Direct Connect setup?",
        "ground_truth": "Sarah Jenkins from the NetSec team"
    },
    {
        "question": "What specific AWS KMS Key ARN must be used for data encryption at rest?",
        "ground_truth": "arn:aws:kms:us-east-1:112233445566:key/db-migration-key-v4"
    },
    {
        "question": "What is the name of the automated AWS Lambda function triggered if the replication lag spikes?",
        "ground_truth": "tg-migration-fallback-handler"
    }
]

def get_compressed_context():
    """Sends the large test history to your FastAPI service to compress it."""
    # Load the high-volume test dataset
    with open("test_history.json", "r") as f:
        payload = json.load(f)
        
    print("[1/4] Sending chat history to local FastAPI server for compression...")
    response = requests.post(FASTAPI_URL, json=payload)
    response.raise_for_status()
    result = response.json()
    
    print(f" -> Original Estimated Tokens: {result.get('original_estimated_tokens')}")
    print(f" -> Compressed Tokens: {result.get('compressed_summary_tokens')}")
    print(f" -> Compression Ratio achieved: {result.get('compression_ratio')}%")
    
    # Extract the system summary field generated by your pipeline
    return result.get("summary")

def query_groq(system_prompt, user_prompt):
    """Helper function to call the Groq API model."""
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    data = {
        "model": "llama-3.1-8b-instant",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.0 # Freeze temperature for deterministic grading
    }
    res = requests.post(GROQ_API_URL, headers=headers, json=data)
    res.raise_for_status()
    return res.json()["choices"][0]["message"]["content"]

def evaluate_accuracy(summary_context):
    """Uses LLM-as-a-Judge framework to grade accuracy retention."""
    print("\n[2/4] Executing QA tests against the compressed summary text...")
    scores = []
    
    for i, test in enumerate(EVALUATION_SUITE):
        print(f"Evaluating Question {i+1}: '{test['question']}'")
        
        # Step A: Ask the model to answer using ONLY the compressed summary context
        qa_system_prompt = f"You are a strict technical assistant. Answer the user's question using ONLY the following context:\n--- START CONTEXT ---\n{summary_context}\n--- END CONTEXT ---"
        generated_answer = query_groq(qa_system_prompt, test["question"])
        
        # Step B: LLM-as-a-Judge compares the answer to the ground truth
        judge_system_prompt = (
            "You are an objective AI Quality Evaluation Judge. You compare a Generated Answer against a Ground Truth Fact.\n"
            "Grade the alignment on a strict integer scale from 0 to 100:\n"
            " - 100: The generated answer contains the exact, accurate factual detail.\n"
            " - 50: The answer is vague or partially correct but missing specific identifiers (like names, numbers, or ARNs).\n"
            " - 0: The answer is completely missing the data point, incorrect, or states it does not know.\n"
            "Output ONLY the raw integer numerical score between 0 and 100. Do not write explanations, markdown, or words."
        )
        
        judge_user_prompt = (
            f"Question: {test['question']}\n"
            f"Ground Truth Correct Fact: {test['ground_truth']}\n"
            f"Generated Answer to Evaluate: {generated_answer}"
        )
        
        score_str = query_groq(judge_system_prompt, judge_user_prompt).strip()
        
        try:
            score = int(score_str)
        except ValueError:
            # Fallback cleaning if the LLM outputs extra characters
            score = int(''.join(filter(str.isdigit, score_str)) or 0)
            
        print(f" -> Ground Truth: {test['ground_truth']}")
        print(f" -> Generated Answer: {generated_answer}")
        print(f" -> Judge Score: {score}/100\n")
        scores.append(score)
        
    # Step C: Final Report Generation
    average_accuracy = sum(scores) / len(scores)
    print("=" * 50)
    print("FINAL CONTEXT COMPRESSION BENCHMARK REPORT")
    print("=" * 50)
    print(f"Target Success Accuracy Criteria: >= 85.0%")
    print(f"Actual Compressed Context Accuracy Retention: {average_accuracy}%")
    if average_accuracy >= 85.0:
        print("STATUS: PASSED - Meets architectural success metrics!")
    else:
        print("STATUS: FAILED - Context degradation detected. Refine prompt constraints.")
    print("=" * 50)

if __name__ == "__main__":
    if not GROQ_API_KEY:
        print("ERROR: Please set your GROQ_API_KEY environment variable before running.")
    else:
        try:
            summary = get_compressed_context()
            evaluate_accuracy(summary)
        except Exception as e:
            print(f"Evaluation failed: {str(e)}")